### ISSUE TITLE
Elaboration on the deploy process and price

### ISSUE THREAD

**Issue by ChristianKniep** [aws-samples/aws-serverless-nextcloud#1]
According to the [aws-cli manual](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html) the command `--output-file` is not available.
```
aws cloudformation package --template-file ecs-nextcloud.yml --s3-bucket <cfn-artifact-bucket-name> --output-file packaged.yaml
```
I reckon for novice Cloudformation users it would be helpful to elaborate on the deployment process. How do I get the parameters configured and how do I actually deploy the stack at the end?

Also, a price estimate for different deployments would be awesome. Like: 
- what is and how much costs the smallest possible deployment (I guess public and everything configured with minimum values) for testing?
- what is and how much costs the smallest production ready deployment?
- what is and how much costs the recommended production deployment?

**Comment by ChristianKniep** [comment]
The Readme has lowercase values for IsolationLevel, the vpc stack allows.
```
  AllowedValues:    
   - PrivateHA 
   - Private  
   - Public
```

**Comment by ChristianKniep** [comment]
Using a JSON file for the parameters I ran into: 
```
Invalid request provided: CreateCluster Invalid Request: Unable to assume the service linked role.
Please verify that the ECS service linked role exists.
```

**Comment by f7o** [comment]
Thanks for bringing these topics up!

I opened a pull request which fixes and improves the documentation:
* FIxed the `aws cloudformation package` parameter typo
* Added an minimal `aws cloudformation deploy` command including parameters
* Corrected the naming of isolation level parameters being the same as within the CFN template
* Added hints regarding the service linked role and linked the official documentation on how to create it: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html#create-service-linked-role

**Comment by f7o** [comment]
We cannot add a section with exact pricing, as costs vary depending on AWS region and lots of other factors when being used in production. There might be workload involving less users but loads of data stored, thousands of users or large volumes being transferred.

To calculate the minimal costs i suggest to have a look into the RDS aurora pricing page. When deploying a test environment with the isolation level `Public` the minimal ACU (Aurora Capacity Units) are 2 (https://aws.amazon.com/rds/aurora/pricing/, section Aurora Serverless v1 Pricing). This is the major cost driver within a minimal deployment.
