### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by ttrentler** [aws-samples/aws-serverless-nextcloud#7]
Great Project!
The documentation assumes that the user has the  AWS CLI installed and is familiar with it as well as CloudFormation using the CLI.
Please consider adding the following links in the documentation as reference . . . 

This project assumes a familiarity with AWS CLI and AWS CloudFormation.  Additional reference can be found at the following links:
[https://aws.amazon.com/cli/](https://aws.amazon.com/cli/)
[https://aws.amazon.com/cloudformation/](https://aws.amazon.com/cloudformation/)

**Comment by f7o** [comment]
Thanks for pointing this out.
Makes sense to add it. In the meantime i investigate on creating a quickstart button usable without CLI usage, while being safe and secure with the source of those templates!
