### ISSUE TITLE
Yaml to json?

### ISSUE THREAD

**Issue by olegbc1** [aws-samples/aws-serverless-nextcloud#9]
Filing mainly to have a discussion around reasons to refactor the current template notation from yaml to json?

**Comment by f7o** [comment]
Can you elaborate on this, what would be the benefits. Please be specific, i do not want to start a general discussion around this topic. Both formats are officially support within AWS CloudFormation.

For me benefits of yaml are clear:
* Better human readability
* Faster coding
* Possibility to add comments

For programmatic processing JSON makes more sense, but you can always use https://github.com/awslabs/aws-cfn-template-flip to convert it if you like.

**Comment by f7o** [comment]
closed due inactivity
